apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  PORT:     {{ .Values.env.PORT     | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
